"""empty message

Revision ID: f75d09e4a119
Revises: 7966b7a27ec8
Create Date: 2018-09-19 20:04:25.991757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f75d09e4a119'
down_revision = '7966b7a27ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
